[PXZ-26] Spring Security
juliabaptista/zalando-e-commerce-shop pull request #7
Opened 2024-01-18 20:34 UTC by juliabaptista

# [PXZ-26] Spring Security

## Technical Tasks:
- [x] Add Spring Security Dependency
- [x] Add JWT Dependency
- [x] Create Jwt Authentication Filter
- [x] Create Jwt Token Provider
- [x] Configure Spring Security

## Technical Tasks - NEED TO BE IMPLEMENTED:
- [ ] Configure security rules
- [ ] JWT authentication

**Blockers:**
- Approval: https://github.com/juliabaptista/zalando-e-commerce-shop/pull/6
- Implementation: UserController + UserController

2024-01-19 16:21 UTC, moseseth commented on src/main/java/de/zalando/helper/JwtTokenProvider.java
> +  private static final String SECRET_KEY = "DyepD0U3QzPmK9b0qNmLznHFs8/tT/a1zxXbdZiodpaGmpjpcxl+ni8CG2hql5qKcbf1QFgJl/25uIDtHjFELIrCfCvcf6ZvnB5hE8Wu8a9l4nNcAM+pl3Jpv3GYsK+lG0hB2+m9IgjFTCIm/53qWQN+gi3
Do not use key inside your code, rather use external config.

2024-01-19 16:21 UTC, moseseth commented on src/main/java/de/zalando/helper/JwtTokenProvider.java
> +        .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 24)) //valid for 24hrs + 1000 milliseconds
This is not 24 hours _1000 * 60 * 24_

2024-01-19 16:21 UTC, moseseth commented on src/main/java/de/zalando/model/entities/User.java
> +  @Column(name = "role_id")
Use name as role rather than role_id as it is the enumerated string.

2024-01-19 16:21 UTC, moseseth commented on src/main/java/de/zalando/filter/JwtAuthenticationFilter.java
> +    final String authHeader = request.getHeader("Authorazation");
```suggestion
    final String authHeader = request.getHeader("Authorization");
```

2024-01-19 17:22 UTC, juliabaptista commented on src/main/java/de/zalando/helper/JwtTokenProvider.java
> +        .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 24)) //valid for 24hrs + 1000 milliseconds
Yes, @moseseth! Great point. 🙂
It's missing another 60.

2024-01-19 17:29 UTC, juliabaptista commented on src/main/java/de/zalando/helper/JwtTokenProvider.java
> +  private static final String SECRET_KEY = "DyepD0U3QzPmK9b0qNmLznHFs8/tT/a1zxXbdZiodpaGmpjpcxl+ni8CG2hql5qKcbf1QFgJl/25uIDtHjFELIrCfCvcf6ZvnB5hE8Wu8a9l4nNcAM+pl3Jpv3GYsK+lG0hB2+m9IgjFTCIm/53qWQN+gi3
@moseseth such as environment variables?

2024-01-22 09:58 UTC, faruka-startsteps requested changes

2024-01-22 09:58 UTC, faruka-startsteps commented on src/main/java/de/zalando/ECommerceShopApplication.java
> +@EntityScan("de.zalando.model.entities")
you can delete this annotation, this is done automatically in spring boot

2024-01-22 09:58 UTC, faruka-startsteps commented on src/main/java/de/zalando/ECommerceShopApplication.java
> +@EnableJpaRepositories("de.zalando.model.repositories")
same

2024-01-22 09:58 UTC, faruka-startsteps commented on src/main/java/de/zalando/config/ApplicationConfig.java
> +  private final UserRepository userRepository;
remove if not used

2024-01-22 11:33 UTC, juliabaptista commented on src/main/java/de/zalando/config/ApplicationConfig.java
> +  private final UserRepository userRepository;
@faruka-startsteps I'm using it afterward to implement UserService!
Just waiting for this PR to be approved to push the rest of the User feature code. 
Could I keep the code here for now?

2024-01-22 11:40 UTC, faruka-startsteps approved these changes
Remove the `@RestController` annotation also from your ECommerceShopApplication and then feel free to merge

2024-01-22 11:53 UTC, merged